### ISSUE TITLE
Add Clippy and Rustfmt by default

### ISSUE THREAD

**Issue by EFanZh** [hecrj/setup-rust-action#1]
Windows and Linux environment has Clippy and Rustfmt installed by default (https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions), so it is natural to expect them to be installed on macOS by default.

**Comment by hecrj** [comment]
I think the idea of this action is to stop relying on the default environments.

The action currently guarantees that `rustup` will be installed and a specific toolchain enabled. Additional components should be installed manually before assuming they exist.

Also, installing `clippy` and `rustfmt` by default will also cause MacOS builds to be slower, even if you do not use them.

That said, I think we could add a `components` input for the action with an empty list as the default value. It should be a non-breaking change.

**Comment by EFanZh** [comment]
I’m OK with adding a `components` input. It should simplify the installation process.
