### ISSUE TITLE
set-env deprecation warnings

### ISSUE THREAD

**Issue by koivunej** [hecrj/setup-rust-action#23]
I see that the @actions/core was already updated to a good version in #21 however the `dist/index.js` was not rebuilt like with a previous dependency update da33d0ff71a74096bb857d0dc8e16c4e3541afc4.

When using the action the deprecation warnings look like:

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by koivunej** [comment]
You were faster with the PR :) I was still trying to understand how should one build a ts repo after I missed `npm build` instructions (should had called `npm run build`).

Can confirm with hecrj/setup-rust-action@cf611166566ceca1d43369d0e656679ea9599c8c there are no more deprecation warnings from this action. Thanks!

**Comment by hecrj** [comment]
@koivunej Glad to help! Thank you for the heads up.

I have released a new version with the fixes and updated the `v1` branch.

**Comment by koivunej** [comment]
Note you tagged the latest release as `v.1.3.4` or `V DOT ONE ...` instead of `v1.3.4` or `V ONE DOT ...`. I am not sure if this hurts some github actions automatic version resolution from `@v1` => latest version.

**Comment by hecrj** [comment]
Fixed!

**Comment by koivunej** [comment]
There was a slight delay but now the latest tarball can be found as well. Thanks again :)
