### ISSUE TITLE
Outdated Node.JS

### ISSUE THREAD

**Issue by vv9k** [hecrj/setup-rust-action#30]
I got a warning on my CI build saying the following:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: hecrj/setup-rust-action

**Comment by CryZe** [comment]
Is there something I need to do for this to be updated on my side? `@v1` seems to still pull in NodeJS 12.

**Comment by hecrj** [comment]
@CryZe My bad! Should be fixed now by 50a120e4d34903c2c1383dec0e9b1d349a9cc2b1.

**Comment by CryZe** [comment]
Thank you :)
