### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jcbhmr** [hecrj/setup-rust-action#36]
Hello! 👋

Is this project still maintained by @hecrj ? I notice that there's been no commits in nearly a year. Should I look elsewhere for a rust setup action?

**Comment by hecrj** [comment]
This is quite a low-maintenance project!

There is a workflow that runs every day and checks everything still works; and it seems to be working fine!

**Comment by jcbhmr** [comment]
The reason I ask is there are three open issues, as well as I had a very long-running PR that got no feedback #34 so I was kinda doing a last-ditch "is this maintained" issue.

Are you open to improvements to this action, or is it in a "no changes, only keep it from breaking" mode?

**Comment by hecrj** [comment]
I'm open to improvements. I was planning to consider your PR when the project needed some attention again (i.e. it breaks or some dependency needs a critical update). It just didn't happen yet.

**Comment by jcbhmr** [comment]
So I take it it's current in a "no changes until it breaks state" right? Ok, that answers my question. Thanks! 👍

**Comment by hecrj** [comment]
Not really. It's currently in a "no changes until I feel they are worth it state", like any other project I maintain for free.
