### ISSUE TITLE
leverage new rustup 1.20 "latest compatible" nightly feature

### ISSUE THREAD

**Issue by softprops** [hecrj/setup-rust-action#7]
An unfortunate but understandable artifact of running rust nightly builds is that some of the tools that also rely on this nightly builds are not always immediately available. I'm feeling that friction in some of my own projects that rely on this action to setup a rust tooling environment. 

Rustup 1.20 [has a feature](https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html#installing-the-latest-compatible-nightly) that explicitly addresses this by finding the most recent rust nightly that has the target tool installed.

I ran a test to validate the `rustup` version [GitHub documents](https://help.github.com/en/github/automating-your-workflow-with-github-actions/software-in-virtual-environments-for-github-actions) which currently 1.19.0 on windows and linux.

I can see that the before and after affect of running this plugin upgrades it to the latest 
![Screen Shot 2019-10-26 at 4 32 20 PM](https://user-images.githubusercontent.com/2242/67625600-3e4d6180-f80e-11e9-842a-4ac089b052cb.png)

What I've found is that rustup does upgrade itself but not until after selecting the nightly version for a given tool and when that version fails the action fails.

![Screen Shot 2019-10-26 at 4 36 32 PM](https://user-images.githubusercontent.com/2242/67625657-db0fff00-f80e-11e9-9e13-0968fae259a7.png)

I think this action could potentially benefit from the new rustup feature but I haven't taken a closer look yet.

**Comment by hecrj** [comment]
Oh, that's great!

> Along with this change, rustup 1.20.0 introduces the --component/-c and --target/-t options to the rustup toolchain install command, allowing you to add components and targets as the toolchain is installed. These flags will also search past nightlies if the current one does not feature all the requested components.

I am guessing we could use these flags to implement the whole action as a single command.
